export default {
  map: (state) => state.map,
  view: (state) => state.view,
  layers: (state) => state.layers,
  layerMission: (state) => state.layerMission,
  sourceMission: (state) => state.sourceMission,
  missions: (state) => state.missions,
  draw: (state) => state.draw,
  isDrawingScheme: (state) => state.isDrawingScheme,
  // planSeeDetail: (state) => state.planSeeDetail,
  colorDraw: (state) => state.colorDraw,
  overlay: (state) => state.overlay,
  sourceBaseMap: (state) => state.sourceBaseMap,
  snap: (state) => state.snap,
  modify: (state) => state.modify,
};
